<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_csseo_xclass"
 *
 * Auto generated by Extension Builder 2019-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tm_csseo_xclass',
    'description' => 'Xclass for og:image s3 assets',
    'category' => 'plugin',
    'author' => 'Simon Ouellet',
    'author_email' => 'simon.ouellet@toumoro.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
